-- Flyway V1: schema inicial

create table if not exists usuario (
    id bigint generated by default as identity primary key,
    username varchar(255) not null,
    password varchar(255) not null,
    role varchar(50) not null,
    ativo boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_usuario_username unique (username)
);

create table if not exists cliente (
    id bigint generated by default as identity primary key,
    nome varchar(255) not null,
    cpf varchar(32) not null,
    email varchar(255),
    telefone varchar(255),
    endereco varchar(1024),
    ativo boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_cliente_cpf unique (cpf)
);

create table if not exists veiculo (
    id bigint generated by default as identity primary key,
    marca varchar(255) not null,
    modelo varchar(255) not null,
    ano integer not null,
    cor varchar(100),
    placa varchar(20) not null,
    renavam varchar(50),
    quilometragem bigint,
    tipoCombustivel varchar(30),
    cambio varchar(30),
    precoCompra numeric(19,2),
    precoVendaSugerido numeric(19,2) not null,
    quantidade_estoque integer not null,
    status varchar(30),
    ativo boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_veiculo_placa unique (placa)
);

create table if not exists venda (
    id bigint generated by default as identity primary key,
    cliente_id bigint not null,
    dataVenda timestamp,
    formaPagamento varchar(30),
    status varchar(30),
    valorTotal numeric(19,2),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_venda_cliente foreign key (cliente_id) references cliente(id)
);

create table if not exists item_venda (
    id bigint generated by default as identity primary key,
    venda_id bigint not null,
    veiculo_id bigint not null,
    quantidade integer not null,
    precoUnitarioNoMomento numeric(19,2) not null,
    subtotal numeric(19,2) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_item_venda_venda foreign key (venda_id) references venda(id),
    constraint fk_item_venda_veiculo foreign key (veiculo_id) references veiculo(id)
);
